default: &default
  adapter: mysql
  encoding: utf8
  username: <%=ENV['C9_USER']%>
  host: <%=ENV['IP']%>

development:
  <<: *default
  database: message_board_development

test:
  <<: *default
  database: message_board_test

production:
  <<: *default
  database: message_board_production